# On pushes to main, run tests on all supported platforms, then release artifacts to MavenCentral

name: 'Push to `main` (Create Release)'

on:
  push:
    branches: ['main']

jobs:
  testOnAll:
    strategy:
      matrix:
        java: [17]
        os: ['ubuntu-latest', 'macos-13', 'windows-latest']
    name: 'Test on ${{ matrix.os }} JDK ${{ matrix.java }}'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          submodules: 'recursive'
      - run: 'git fetch --prune --unshallow --tags'
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'temurin'
          java-version: '${{ matrix.java }}'
      - name: 'Run checks with Gradle'
        run: './gradlew check --no-daemon --stacktrace -Prelease -PorchidEnvironment=prod'

  publishArtifactsOnMacOs:
    runs-on: 'macos-13'
    needs: ['testOnAll']
    env:
      GITHUB_ACTOR: '${{ github.actor }}'
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      OSSRH_USERNAME: '${{ secrets.OSSRH_USERNAME }}'
      OSSRH_PASSWORD: '${{ secrets.OSSRH_PASSWORD }}'
      STAGING_PROFILE_ID: '${{ secrets.STAGING_PROFILE_ID }}'
      SIGNING_KEY_ID: '${{ secrets.SIGNING_KEY_ID }}'
      SIGNING_KEY: '${{ secrets.SIGNING_KEY }}'
      SIGNING_PASSWORD: '${{ secrets.SIGNING_PASSWORD }}'
      JB_PRIVATE_KEY: '${{ secrets.JB_PRIVATE_KEY }}'
      JB_CHAIN: '${{ secrets.JB_CHAIN }}'
      JB_PASSPHRASE: '${{ secrets.JB_PASSPHRASE }}'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          submodules: 'recursive'
      - run: 'git fetch --prune --unshallow --tags'
      - name: 'Set up JDK 11'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'temurin'
          java-version: 17
      - name: 'Assemble Artifacts'
        run: './gradlew assemble --stacktrace -Prelease -PorchidEnvironment=prod'
      - name: 'Open Sonatype Staging Repository'
        run: './gradlew openSonatypeStagingRepository --stacktrace -Prelease -PorchidEnvironment=prod'
      - name: 'Publish Artifacts'
        run: './gradlew publishAllPublicationsToMavenCentralRepository --stacktrace -Prelease -PorchidEnvironment=prod'
      - name: 'Build Documentation'
        run: './gradlew :docs:mkdocsBuild --stacktrace -Prelease'
      - name: 'Close Sonatype Staging Repository'
        run: './gradlew closeSonatypeStagingRepository --stacktrace -Prelease -PorchidEnvironment=prod'
