# On pushes to main, run tests on all supported platforms. If all tests pass, then publish release artifacts and
# update Orchid documentation site.

name: 'Push to `main` (Create Release)'

on:
  push:
    branches: ['main', 'docs']

jobs:
  buildDocumentationSite:
    runs-on: 'macos-latest'
    env:
      GITHUB_ACTOR: '${{ github.actor }}'
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    steps:
      - name: 'Build Documentation'
        run: './gradlew :docs:mkdocsBuild --stacktrace -Prelease'
      - name: 'Upload static files as artifact'
        uses: 'actions/upload-pages-artifact@v3'
        with:
          path: docs/build/mkdocs/
  deploy:
    runs-on: 'ubuntu-latest'
    needs: ['buildDocumentationSite']
    permissions:
      pages: 'write'
      id-token: 'write'
    environment:
      name: 'github-pages'
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 'Deploy to GitHub Pages'
        uses: 'actions/deploy-pages@v4'

